### ISSUE TITLE
Add groups/subgroups to Saved Projects

### ISSUE THREAD

**Issue by stefanobartoletti** [L13/vscode-projects#21]
First of all thank you for this addon, it is a great way to organize projects inside VS Code, and in fact also all your other extensions are great.

I think it would be useful to be able to further organize projects in groups/subgroups when saving them. At the moment I'm using a name pattern (something like `[group name] project name`, so `[work] website development` or `[course] vue framework course`), but a proper way to categorize projects would be great. Ideally one could also be able to click on the group name to fold/unfold it, and maybe to customize the group icon.

As an example, something like this

![Screenshot_20210131_193413](https://user-images.githubusercontent.com/36746429/106394636-d5d03580-63fd-11eb-8ee0-76d76b6a9585.png)

**Comment by L13** [comment]
Hi and thank you.

I had a similar idea about grouping favorites. The advantage is that you can group everything. It would work like favorites in Diff Folders. So you can also open all projects at once in a group. I would try this first.

**Comment by stefanobartoletti** [comment]
I understand. I suggested saved projects because I don't really use favorites that much, but I understand your reasoning.

**Comment by L13** [comment]
Hi, I want to give you a short update. I have implemented groups in the next version, which allows to group favorites **and** workspaces (git, vscode, subfolder). These groups are also available for every kind of sorting. Subgroups are not available, because I want to keep it simple.

On the other side I have rewritten/refactored nearly the whole source. So I have to test a lot until I release the new version. This kind of refactoring also affects the extension Diff Folders.

These extensions are spare time projects so I make no promises when everything is done. But maybe they are available at end of march or april.

**Comment by stefanobartoletti** [comment]
Thank you for your effort, these extensions are really useful and top quality, and I wasn't aware that they were developed by a single person.

No need to hurry, and really, thank you.

**Comment by L13** [comment]
Hi, version 0.18.0 is now available and supports groups. I started in the QA phase with the next feature to provide more options to organise projects. stay tuned. ^^

**Comment by stefanobartoletti** [comment]
Just updated and tested, it is exactly what I had in mind!
Thank you!
