### ISSUE TITLE
Idea - add comments/url's to projects

### ISSUE THREAD

**Issue by Escalion86** [L13/vscode-projects#35]
Can you add comments to projects?
Maybe if RMB click on Project and then:
 => Readme.md open (if exist)
or 
=> http://github.... open

I thing better if you can add some links to project with specifed names to show in dropdown menu in project

**Comment by L13** [comment]
Hi, I had similar ideas for adding more information to projects like urls and so on, but I declined it for now because it requires an additional ui/view to manage all that stuff otherwise there will be to much actions in the context menu. The version with the right mouse button is technically not possible because the context menu labels are static.

Right now I'm working on support for new features like trusted workspaces or virtual workspaces which the vscode team is providing in the next months otherwise my extensions will not work properly with the new vscode versions. Which also means I have no time for adding new other features in the next months, because I have to change a lot. The extensions are spare time projects, so there are no time tables or anything like this when things are done or possible. Sorry for the bad news.

Your idea sounds like you need something like bookmarks you want to add to your projects. I recommend to look for other extensions which are doing exactly this stuff.

**Comment by Escalion86** [comment]
Thanx!!!
